# This config file is not very tidy 
# because of appending different config files on each other
baseurl = "/"
languageCode = "en-us"
title = "T.E.G.'s Blog"
author = "TEG"
theme = "hugo-tanka"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

canonifyurls = true
#pygmentsstyle      = "vs"
#pygmentscodefences = true

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/tahirenesgedik"

[params]
      intro = true
    # headline = "My headline"
    # description = "A blog for future."
      sitename = "T.E.G.'s Blog"

    # options for highlight.js (version, additional languages, and theme)
    #highlightjsVersion = "9.11.0"
    #highlightjsCDN = "//cdn.bootcss.com"
    #highlightjsLang = ["r", "yaml"]
    #highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
#   dateFormat = "Mon, Jan 2, 2006"

#   [params.logo]
#   url = "logo.png"
#   width = 50
#   height = 50
#   alt = "Logo"

