---
title: "Sources"
author: T.E.G.
date: "2018-02-04T13:59:48"
slug: sources
categories: []
tags: []
---

This page contains links to useful sources on statistics, `R`, and other software packages. 

* [blogdown: Creating Websites with R Markdown by Xie, Thomas, and Hill ](https://bookdown.org/yihui/blogdown/) (I use `blogdown` to create this website.)
* [CRAN Task View: Statistics for the Social Sciences](https://cran.r-project.org/web/views/SocialSciences.html)
* [CRAN Task Views](https://cran.r-project.org/web/views/)
* [Cross Validated](https://stats.stackexchange.com)
* [Data Visualization: A Practical Introduction by Healy](http://socviz.co/)
* [Forecasting: Principles and Practice by Hyndman and Athanasopoulos](https://otexts.org/fpp2/)
* [Math Camp Lectures - UW CSSS](http://csss.washington.edu/academics/math-camp/lectures)
* [Personality Project](http://personality-project.org/index.html)
* [Quick-R](http://www.statmethods.net/)
* [R for Data Science by Grolemund and Wickham](http://r4ds.had.co.nz/)
* [R Markdown: The Definitive Guide by Xie, Allaire, and Grolemund ](https://bookdown.org/yihui/rmarkdown/)
* [R Weekly](https://rweekly.org/)
* [R-statistics.co](http://r-statistics.co/)
* [Rseek](https://rseek.org/)
* [RStudio Community](https://community.rstudio.com/)
* [Seeing Theory](http://students.brown.edu/seeing-theory/)
* [Statistical Modeling, Causal Inference, and Social Science (a.k.a., Andrew Gelman's Blog)](http://andrewgelman.com)
* [Statistical Rethinking with brms, ggplot2, and the tidyverse by Solomon Kurz](https://bookdown.org/ajkurz/Statistical_Rethinking_recoded/)
* [Statistics, R, Data, Science by Michael Clark](http://m-clark.github.io/)
* [STHDA (Statistical Tools for High-throughput Data Analysis)](http://www.sthda.com/english/)
* [The R Graph Gallery](http://www.r-graph-gallery.com/)
* [UCLA IDRE - Annotated Output](https://stats.idre.ucla.edu/other/annotatedoutput/)

### R package sources

* [An Introduction to Margins](https://cran.r-project.org/web/packages/margins/vignettes/Introduction.html)
* [DeclareDesign](http://declaredesign.org/)
* [The Easyverse](https://github.com/easystats/easystats)
* [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)
* [SjPlot-Package](https://strengejacke.github.io/sjPlot/)
* [Stargazer Cheat Sheet](http://www.jakeruss.com/cheatsheets/stargazer/)
* [The lavaan Project](http://lavaan.ugent.be/)
* [Tidyverse](https://www.tidyverse.org/)
* [Zelig - Everyone's Statistical Software](https://zeligproject.org/)





