---
title: Binomial GLM Predicted Probabilities
author: T.E.G.
date: "2018-02-04T13:59:50"
slug: rmd-exmp
categories: []
tags: []
---

Here is an example of binomial glm (e.g., logistic regression):

```{r model, echo=TRUE, eval=TRUE}
df <- car::Mroz # U.S. Women's Labor-Force Participation data
glmfit <- glm(lfp ~ k5 + age + inc + lwg, df, family=binomial)
summary(glmfit)
```

Calculating Predicted Probabilities for representative values of `k5`:

```{r predprod, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
# Take mean values of the other predictors
mean_val_pred <- df %>% 
  select(age, inc, lwg) %>% 
  map_df(., mean)

# Create new data frame for prediction
preddf <- with(df, data.frame(k5=c(0:3), mean_val_pred))

# Calculate predicted probabilities
preddf$pred <- predict(glmfit, preddf, type = "response")
preddf
```

Here is how to plot predicted probabilities using `ggplot2`:

```{r plot, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
library(hrbrthemes)

preddf %>% 
  ggplot(aes(k5, pred)) +
  geom_point() +
  geom_line() +
  labs(y="Predicted Probabilities", 
       x="Number of children 5 years old or younger.", 
       title="Predicted Probabilities for Labor Force Participation") +
  theme_ipsum_rc() # from hrbrthemes package


```

### With a grouping variable

We can repeat the same analysis, but this time using a grouping variable (`wc`). 

```{r predprod2, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
df <- car::Mroz # U.S. Women's Labor-Force Participation data
glmfit <- glm(lfp ~ k5 + wc + age + inc + lwg, df, family=binomial)

# Take mean values of the other predictors
mean_val_pred <- df %>% 
  select(age, inc, lwg) %>% 
  map_df(., mean)

# Create new data frame for prediction
# Note that wc is added to the data frame
preddf <- with(df, data.frame(k5=c(0:3), wc=c(rep("yes",4), rep("no",4)), mean_val_pred))

# Calculate predicted probabilities
preddf$pred <- predict(glmfit, preddf, type = "response")
preddf
```


```{r plot2, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}

preddf %>% 
  ggplot(aes(k5, pred, color=wc)) +
  geom_point() +
  geom_line() +
  labs(y="Predicted Probabilities", 
       x="Number of children 5 years old or younger.", 
       title="Predicted Probabilities for Labor Force Participation",
       color="Wife's College\nAttendance") +
  theme_ipsum_rc() + # from hrbrthemes package 
  theme(legend.position="bottom")
```


















