---
title: "Maximum Likelihood: Finding the Top of a Hill"
author: T.E.G.
date: '2018-02-04T18:34:54'
slug: climbing
categories: []
tags: []
bibliography: references.bib
---

I think one of the most intuitive ways of describing maximum likelihood estimation (especially to the beginners) can be found in [@Long2014]:

> For all but the simplest models, the only way to find the maximum likelihood function is by numerical methods. Numerical methods are the mathematical equivalent of how you would find the top of a hill if you were blindfolded and knew only the slope of the hill at the spot where you are standing and how the slope at that spot is changing which you could figure out by poking your foot in each direction. The search begins with starts values corresponding to your location as you start your climb. From the start position, the slope of the likelihood function and the rate of change in the slope determine the next guess for the paramters. The process continues to iterate until the maximum of the likelihood function function is found, called, convergence, and the resulting estimates are reported [@Long2014, pp.84]


#### **References**
